ifeq ($(CONFIG_PLATFORM_ADLINK_MTK), y)

EXTRA_CFLAGS += -DCONFIG_PLATFORM_ADLINK_MTK
EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT

ARCH ?= arm64

CROSS_COMPILE ?= $(CROSS_COMPILE)

KSRC ?= $(KERNEL_SRC)


EXTRA_CFLAGS += -DCONFIG_RXBUF_NUM_1024
EXTRA_CFLAGS += -DCONFIG_TX_SKB_ORPHAN
EXTRA_CFLAGS += -DCONFIG_SWCAP_SYNC_WIN

endif

